$terminal = alacritty
$browser = zen-browser
$fileManager = nautilus
$menu = rofi -show drun
$command = rofi -show run

$config = ~/.config/hypr/conf

source = $config/monitors.conf
source = $config/autostart.conf
source = $config/environment.conf
source = $config/lookAndFeel.conf
source = $config/input.conf
source = $config/keybindings.conf
source = $config/windowsAndWorkspaces.conf

