splash = false

preload = /home/juderozario/wallpaper/wallpaper.png
preload = /home/juderozario/wallpaper/japan-background-digital-art.jpg

wallpaper = DP-1,/home/juderozario/wallpaper/wallpaper.png
wallpaper = HDMI-A-1,/home/juderozario/wallpaper/japan-background-digital-art.jpg
