
name: chat
root: ~/Projects/SimpleChatApp

windows:
  - frontend:
      root: ~/Projects/SimpleChatApp/frontend
      panes:
        - nvim
  - server:
      root: ~/Projects/SimpleChatApp/backend
      panes:
        - nvim
  - run:
      layout: even-horizontal
      panes:
        - app:
            - cd frontend && npm run dev
        - server:
            - cd backend && go run main.go

